version: '3.7'

services:
  db:
    image: postgres:11.3
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6.0.6-alpine
    ports:
      - '127.0.0.1:${REDIS_PORT}:6379'

  api:
    build:
      context: ..
      dockerfile: .docker/api/Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_HOST: '${DB_HOST}'
      DB_NAME: '${DB_NAME}'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      REDIS_DB: '${REDIS_DB}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ..
      dockerfile: .docker/worker/Dockerfile
    environment:
      DB_HOST: '${DB_HOST}'
      DB_NAME: '${DB_NAME}'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      REDIS_DB: '${REDIS_DB}'
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - api

volumes:
  db:
