version: '3.7'

services:
  api:
    build:
      target: dev
    volumes:
      - api:/api
  worker:
    build:
      target: dev
    volumes:
      - api:/worker

volumes:
  api:
    driver_opts:
      type: none
      device: '${PWD}/..'
      o: bind

