version: '3.7'

services:
  db:
    image: postgres:11.3
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: .docker/api/Dockerfile
    ports:
      - '8000:8000'
    environment:
      DB_HOST: '${DB_HOST}'
      DB_NAME: '${DB_NAME}'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DJANGO_SECRET_KEY: '${DJANGO_SECRET_KEY}'
      DJANGO_SETTINGS_MODULE: '${DJANGO_SETTINGS_MODULE}'
    depends_on:
      - db

volumes:
  db:
